In [9]:
!pip install -U scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-0.23.1-cp37-cp37m-macosx_10_9_x86_64.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB 3.1 MB/s eta 0:00:01
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages (from scikit-learn) (1.17.2)
Requirement already satisfied, skipping upgrade: scipy>=0.19.1 in /Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages (from scikit-learn) (1.4.1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages (from scikit-learn) (0.13.2)
ERROR: simpletransformers 0.28.5 has requirement transformers>=2.9.1, but you'll have transformers 2.1.1 which is incompatible.
ERROR: cdqa 1.3.9 has requirement scikit-learn==0.21.2, but you'll have scikit-learn 0.23.1 which is incompatible.
ERROR: cdqa 1.3.9 has requirement torch==1.2.0, but you'll have torch 1.5.1 which is incompatible.
Installing collected packages: threadpoolctl, scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.21.2
    Uninstalling scikit-learn-0.21.2:
      Successfully uninstalled scikit-learn-0.21.2
Successfully installed scikit-learn-0.23.1 threadpoolctl-2.1.0
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/Users/saloniparekh/opt/anaconda3/bin/python -m pip install --upgrade pip' command.

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Last_89_ANNFormat.csv')

In [4]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Country Name,Year,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,...,"Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Label
0,11160,0,Pakistan,1960,..,..,..,..,..,..,...,..,..,..,20.3931892012994,..,..,..,22.104,..,0.0
1,11161,0,Pakistan,1961,..,..,..,..,..,..,...,..,..,..,20.2314791209912,..,..,..,22.501,..,0.0
2,11162,0,Pakistan,1962,..,..,..,..,..,..,...,..,..,..,21.0913520097442,..,..,..,22.751,..,0.0
3,11163,0,Pakistan,1963,..,..,..,..,..,..,...,..,..,..,23.9887538545257,..,..,..,23.002,..,0.0
4,11164,0,Pakistan,1964,..,..,..,..,..,..,...,..,..,..,23.1259582022109,..,..,..,23.256,..,0.0

In [5]:
df = df.replace('..', np.nan)
df.head()

,Unnamed: 0,Unnamed: 0.1,Country Name,Year,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,...,"Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Label
0,11160,0,Pakistan,1960,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.3931892012994,NaN,NaN,NaN,22.104,NaN,0.0
1,11161,0,Pakistan,1961,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.2314791209912,NaN,NaN,NaN,22.501,NaN,0.0
2,11162,0,Pakistan,1962,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,21.0913520097442,NaN,NaN,NaN,22.751,NaN,0.0
3,11163,0,Pakistan,1963,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,23.9887538545257,NaN,NaN,NaN,23.002,NaN,0.0
4,11164,0,Pakistan,1964,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,23.1259582022109,NaN,NaN,NaN,23.256,NaN,0.0

In [10]:
df_pak = df[df['Country Name'] == 'Pakistan'].iloc[:,3:]
df_pak.head()

,Year,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),...,"Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Label
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.3931892012994,NaN,NaN,NaN,22.104,NaN,0.0
1,1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.2314791209912,NaN,NaN,NaN,22.501,NaN,0.0
2,1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,21.0913520097442,NaN,NaN,NaN,22.751,NaN,0.0
3,1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,23.9887538545257,NaN,NaN,NaN,23.002,NaN,0.0
4,1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,23.1259582022109,NaN,NaN,NaN,23.256,NaN,0.0

In [34]:
%%time
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
df_pak_filled = imputer.fit_transform(df_pak)

CPU times: user 164 ms, sys: 6.21 ms, total: 170 ms
Wall time: 167 ms

In [35]:
df_pak_filled_df = pd.DataFrame(data = df_pak_filled)

In [39]:
df_pak_filled_df

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,128
0,1960.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,20.393189,20.742523,43.5,33.666667,22.104,46.773333,0.0
1,1961.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,20.231479,20.742523,43.5,33.666667,22.501,46.773333,0.0
2,1962.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,21.091352,20.742523,43.5,33.666667,22.751,46.773333,0.0
3,1963.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,23.988754,20.742523,43.5,33.666667,23.002,46.773333,0.0
4,1964.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,23.125958,20.742523,43.5,33.666667,23.256,46.773333,0.0
5,1965.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,24.041084,20.742523,43.5,33.666667,23.511,46.773333,0.0
6,1966.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,19.194085,20.742523,43.5,33.666667,23.769,46.773333,0.0
7,1967.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,20.494570,20.742523,43.5,33.666667,24.028,46.773333,0.0
8,1968.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,19.132546,20.742523,43.5,33.666667,24.289,46.773333,0.0
9,1969.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.015567e+06,66.466667,18.266667,...,285.50,0.25,2.112743,17.480471,20.742523,43.5,33.666667,24.552,46.773333,0.0
10,1970.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.335900e+06,66.466667,18.266667,...,285.50,0.25,2.550403,17.966116,20.742523,43.5,33.666667,24.817,46.773333,0.0
11,1971.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.085600e+06,66.466667,18.266667,...,285.50,0.25,1.648717,18.202044,20.742523,43.5,33.666667,25.084,46.773333,0.0
12,1972.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,6.252000e+05,66.466667,18.266667,...,285.50,0.25,2.139110,15.821338,20.742523,43.5,33.666667,25.353,31.620001,0.0
13,1973.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,8.052000e+05,66.466667,18.266667,...,285.50,0.25,3.771280,28.979731,20.742523,43.5,33.666667,25.671,46.773333,0.0
14,1974.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.047700e+06,66.466667,18.266667,...,285.50,0.25,2.641829,30.830174,20.742523,43.5,33.666667,26.005,46.773333,0.0
15,1975.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.451800e+06,66.466667,18.266667,...,285.50,0.25,2.741542,32.388045,20.742523,43.5,33.666667,26.341,46.773333,0.0
16,1976.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,1.947400e+06,66.466667,18.266667,...,285.50,0.25,2.868737,28.945875,16.382253,43.5,33.666667,26.681,54.349998,0.0
17,1977.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,2.303700e+06,66.466667,18.266667,...,285.50,0.25,2.845534,27.200363,21.301317,43.5,33.666667,27.023,54.349998,0.0
18,1978.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,2.656300e+06,66.466667,18.266667,...,285.50,0.25,2.759812,27.918042,24.544000,43.5,33.666667,27.368,54.380001,0.0
19,1979.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,2.773100e+06,66.466667,18.266667,...,285.50,0.25,3.096908,32.864582,20.345121,43.5,33.666667,27.715,55.160000,0.0
20,1980.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,3.029200e+06,66.466667,18.266667,...,285.50,0.25,3.406646,35.896899,26.256281,43.5,33.666667,28.066,53.639999,0.0
21,1981.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,3.096800e+06,66.466667,18.266667,...,285.50,0.25,3.029125,35.168011,22.258297,43.5,33.666667,28.380,53.090000,0.0
22,1982.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,3.328800e+06,66.466667,18.266667,...,285.50,0.25,2.670313,31.322283,26.329290,43.5,33.666667,28.619,53.200001,0.0
23,1983.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,3.466900e+06,66.466667,18.266667,...,285.50,0.25,4.230150,34.691962,28.652276,43.5,33.666667,28.859,50.970001,0.0
24,1984.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,3.641900e+06,66.466667,18.266667,...,285.50,0.25,3.675517,33.362633,24.470767,43.5,33.666667,29.101,50.970001,0.0
25,1985.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,3.839400e+06,66.466667,18.266667,...,285.50,0.25,4.242566,33.170746,23.891904,43.5,33.666667,29.344,50.840000,0.0
26,1986.0,70.375756,6.451320,3.194313,59.973720,100.0,100.000000,4.127200e+06,66.466667,18.266667,...,285.50,0.25,4.640283,32.406731,25.125121,43.5,33.666667,29.588,51.540001,0.0
27,1987.0,70.396439,11.290743,7.814099,59.973720,100.0,100.000000,4.434400e+06,66.466667,18.266667,...,285.50,0.25,5.103263,32.897102,21.594127,43.5,33.666667,29.833,51.290001,0.0
28,1988.0,70.375756,5.065376,1.849001,59.973720,100.0,100.000000,4.889400e+06,66.466667,18.266667,...,285.50,0.25,4.629615,33.284226,20.610329,43.5,33.666667,30.080,51.490002,0.0
29,1989.0,70.375756,2.997842,-0.080161,59.973720,100.0,100.000000,5.009000e+06,66.466667,18.266667,...,285.50,0.25,4.458354,34.421659,17.340211,43.5,33.666667,30.327,41.799999,0.0
30,1990.0,70.375756,4.272201,1.235473,59.973720,100.0,100.000000,5.180200e+06,66.466667,18.266667,...,285.50,0.25,4.519947,35.034576,12.033070,43.5,33.666667,30.576,49.790001,0.0
31,1991.0,70.375756,1.344296,-1.519806,59.973720,100.0,100.000000,5.197700e+06,66.000000,18.800000,...,285.50,0.25,4.207187,35.419655,12.483670,43.5,30.500000,30.826,47.500000,0.0
32,1992.0,70.375756,5.605697,2.701613,59.973720,100.0,100.000000,5.680600e+06,66.466667,18.266667,...,285.50,0.25,4.670819,37.694540,8.640313,43.5,33.666667,31.077,47.689999,0.0
33,1993.0,70.375756,1.345311,-1.403319,59.973720,100.0,100.000000,5.647100e+06,66.466667,18.266667,...,285.50,0.25,4.569259,38.499317,7.813417,43.5,33.666667,31.329,47.450001,0.0
34,1994.0,70.375756,3.576080,0.756909,59.973720,100.0,100.000000,5.663700e+06,66.466667,18.266667,...,285.50,0.25,6.548058,35.057724,8.592013,43.5,33.666667,31.582,46.939999,0.0
35,1995.0,70.375756,7.679548,4.709475,59.973720,100.0,100.000000,5.342600e+06,66.466667,18.266667,...,285.50,0.25,5.249873,36.132754,7.657808,43.5,33.666667,31.836,48.380001,0.0
36,1996.0,70.375756,3.416043,0.514976,59.973720,100.0,100.000000,5.375000e+06,66.466667,19.666667,...,285.50,0.25,5.231522,38.330127,6.815328,43.5,33.666667,32.092,49.750001,0.0
37,1997.0,70.375756,0.534376,-2.310146,59.973720,100.0,100.000000,5.882500e+06,66.466667,18.000000,...,285.50,0.25,6.629122,36.852266,7.149236,43.5,37.500000,32.348,50.490002,0.0
38,1998.0,70.460000,5.949945,2.975339,59.973720,100.0,100.000000,5.414100e+06,66.466667,19.666667,...,285.50,0.25,3.736670,34.011725,6.915739,43.5,33.666667,32.585,50.380001,0.0
39,1999.0,70.297935,2.372600,-0.419910,59.973720,100.0,100.000000,5.850000e+06,66.466667,18.000000,...,285.50,0.25,4.716458,32.319963,6.060606,43.5,33.666667,32.783,49.913334,0.0
40,2000.0,70.369331,-8.951261,-11.330057,59.973720,200.0,200.000000,5.293541e+06,66.466667,21.333333,...,285.50,0.25,3.541068,25.363430,6.511254,43.5,33.666667,32.982,48.869999,0.0
41,2001.0,70.431381,3.732388,1.149479,59.973720,200.0,200.000000,6.011849e+06,66.466667,23.000000,...,285.50,0.25,3.820915,27.630045,6.978588,43.5,33.000000,33.180,49.346667,0.0
42,2002.0,70.479156,3.988629,1.505345,59.973720,500.0,500.000000,4.141009e+06,66.466667,23.000000,...,285.50,0.25,3.587677,27.633807,6.680441,43.5,31.900000,33.380,48.790001,1.0
43,2003.0,70.507721,8.223478,5.718415,59.973720,500.0,500.000000,4.522110e+06,66.466667,25.666667,...,285.50,0.25,3.252887,29.796396,8.431237,43.5,31.900000,33.580,49.053333,0.0
44,2004.0,70.512154,6.133011,3.713606,59.973720,1600.0,1600.000000,5.097477e+06,66.466667,36.666667,...,285.50,0.25,3.897979,27.549625,10.431175,43.5,31.900000,33.781,49.500000,0.0
45,2005.0,70.490608,5.682897,3.283625,59.973720,9300.0,9600.000000,5.364134e+06,66.466667,31.000000,...,285.50,0.25,2.016215,32.154429,8.969936,43.5,26.100000,33.982,49.695567,0.0
46,2006.0,70.453568,12.842713,10.284413,61.588980,8900.0,9200.000000,5.714831e+06,66.466667,56.000000,...,285.50,0.25,1.660989,35.681730,11.517615,43.5,26.100000,34.184,49.740601,1.0
47,2007.0,70.414604,4.787634,2.423795,58.872510,11000.0,11000.000000,5.439144e+06,69.000000,38.800000,...,285.50,0.25,1.721458,32.990429,12.631579,43.5,25.200000,34.387,49.846100,1.0
48,2008.0,70.387283,0.159635,-2.081574,59.459670,13000.0,13000.000000,5.605758e+06,72.533333,38.000000,...,285.50,0.25,1.745770,35.594201,12.554629,43.5,26.100000,34.590,49.872299,1.0
49,2009.0,70.385170,5.395969,3.068215,59.857250,14000.0,14000.000000,5.303268e+06,72.533333,41.000000,...,285.50,0.25,2.008913,32.071848,10.785091,43.5,26.100000,34.793,50.264900,0.0
50,2010.0,70.421844,3.356702,1.110684,59.402250,13000.0,14000.000000,6.588114e+06,72.533333,40.666667,...,285.50,0.20,2.345789,32.868927,10.406005,43.5,26.100000,34.997,50.664398,1.0
51,2011.0,70.507156,4.000407,1.779074,58.889830,13000.0,14000.000000,7.940545e+06,72.533333,43.000000,...,285.50,0.25,1.333870,32.939905,10.789702,43.5,20.866667,35.202,50.370499,1.0
52,2012.0,70.636093,2.866459,0.701885,56.992250,14000.0,15000.000000,7.973906e+06,72.533333,51.000000,...,285.50,0.25,2.077861,32.805502,10.577223,43.5,20.866667,35.408,50.321899,1.0
53,2013.0,70.799934,4.707640,2.527982,56.168560,15000.0,16000.000000,7.833901e+06,64.400000,52.100000,...,285.50,0.25,2.849255,33.333599,8.703536,43.5,20.100000,35.613,49.930801,0.0
54,2014.0,70.989944,5.972158,3.777962,50.605830,16000.0,17000.000000,7.670348e+06,72.533333,48.700000,...,285.50,0.25,1.864696,30.901245,7.939189,43.5,20.866667,35.819,50.065800,0.0
55,2015.0,71.197411,6.218773,4.024305,38.656680,17000.0,18000.000000,8.467827e+06,72.533333,48.700000,...,285.50,0.25,1.432092,27.654673,9.164498,42.0,18.233333,36.026,50.170300,0.0
56,2016.0,71.413597,7.329736,5.115793,34.910800,18000.0,19000.000000,9.628354e+06,72.533333,57.466667,...,285.50,0.30,1.460673,25.306232,8.735257,43.5,18.233333,36.234,50.055634,1.0
57,2017.0,70.790000,5.326919,3.163907,35.097490,19000.0,20000.000000,7.260769e+06,72.533333,57.466667,...,285.50,0.25,2.141776,25.852837,7.823196,45.0,17.300000,36.442,49.715833,0.0
58,2018.0,71.091547,5.126609,2.987397,32.246310,20000.0,22000.000000,6.880637e+06,84.200000,69.300000,...,285.15,0.25,1.848437,29.043322,8.306904,43.5,17.300000,36.666,48.911400,0.0
59,2019.0,71.098381,5.927755,3.755699,34.084867,19000.0,20333.333333,7.923253e+06,72.533333,57.466667,...,124.90,0.25,1.816962,30.438208,10.816137,43.5,18.233333,36.907,49.715833,1.0

In [38]:
df_pak_filled_df.iloc[:,2]

0      6.451320
1      6.451320
2      6.451320
3      6.451320
4      6.451320
5      6.451320
6      6.451320
7      6.451320
8      6.451320
9      6.451320
10     6.451320
11     6.451320
12     6.451320
13     6.451320
14     6.451320
15     6.451320
16     6.451320
17     6.451320
18     6.451320
19     6.451320
20     6.451320
21     6.451320
22     6.451320
23     6.451320
24     6.451320
25     6.451320
26     6.451320
27    11.290743
28     5.065376
29     2.997842
30     4.272201
31     1.344296
32     5.605697
33     1.345311
34     3.576080
35     7.679548
36     3.416043
37     0.534376
38     5.949945
39     2.372600
40    -8.951261
41     3.732388
42     3.988629
43     8.223478
44     6.133011
45     5.682897
46    12.842713
47     4.787634
48     0.159635
49     5.395969
50     3.356702
51     4.000407
52     2.866459
53     4.707640
54     5.972158
55     6.218773
56     7.329736
57     5.326919
58     5.126609
59     5.927755
Name: 2, dtype: float64

In [37]:
df_pak['Access to electricity (% of population)']

0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
5                   NaN
6                   NaN
7                   NaN
8                   NaN
9                   NaN
10                  NaN
11                  NaN
12                  NaN
13                  NaN
14                  NaN
15                  NaN
16                  NaN
17                  NaN
18                  NaN
19                  NaN
20                  NaN
21                  NaN
22                  NaN
23                  NaN
24                  NaN
25                  NaN
26                  NaN
27     11.2907430468447
28     5.06537600547345
29     2.99784152420581
30     4.27220143155806
31     1.34429589199527
32     5.60569714298613
33     1.34531098210753
34     3.57608025208262
35     7.67954820529559
36     3.41604278728052
37    0.534375643931668
38     5.94994543616556
39     2.37259952024165
40    -8.95126128297882
41     3.73238840134351
42     3.98862858085775
43     8.22347834522571
44     6.13301098110803
45     5.68289702626232
46     12.8427125720052
47      4.7876339087851
48    0.159634844603133
49     5.39596881969105
50     3.35670249688292
51     4.00040723026748
52     2.86645901068819
53     4.70763963282465
54     5.97215825842392
55     6.21877345836977
56     7.32973638158447
57      5.3269186870601
58     5.12660905799463
59                  NaN
Name: Access to electricity (% of population), dtype: object

In [29]:
dict = {"First" : [100, 90, np.nan, 95, np.nan], "Second" : [30, 45, 56, np.nan, np.nan], "Third" : [np.nan, 40, 80, 98, np.nan]}
dx = pd.DataFrame(dict)
dx

   First  Second  Third
0  100.0    30.0    NaN
1   90.0    45.0   40.0
2    NaN    56.0   80.0
3   95.0     NaN   98.0
4    NaN     NaN    NaN

In [30]:
impx = KNNImputer(n_neighbors=2)
x = imputer.fit_transform(dx)
x

array([[100.        ,  30.        ,  72.66666667],
       [ 90.        ,  45.        ,  40.        ],
       [ 95.        ,  56.        ,  80.        ],
       [ 95.        ,  43.66666667,  98.        ],
       [ 95.        ,  43.66666667,  72.66666667]])