In [1]:
import pandas as pd
import numpy as np

In [81]:
df = pd.read_csv("Baseline_Anomaly_New.csv")
df.drop('Unnamed: 0', axis = 1, inplace = True)
df.head()

,Country Name,Year,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",...,"Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Label
0,Afghanistan,2000,NaN,NaN,NaN,NaN,500.0,500.0,149705.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.078,NaN,1.0
1,Afghanistan,2001,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.169,NaN,1.0
2,Afghanistan,2002,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.261,NaN,1.0
3,Afghanistan,2003,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.353,NaN,1.0
4,Afghanistan,2004,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.500,NaN,0.0

In [82]:
dataframe = df.drop(['Country Name', 'Year', 'Label'], axis = 1)
dataframe.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Specialist surgical workforce (per 100,000 population)","Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population)
0,NaN,NaN,NaN,NaN,500.0,500.0,149705.0,NaN,12.4,NaN,...,5.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.078,NaN
1,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.169,NaN
2,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.261,NaN
3,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,14.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.353,NaN
4,NaN,NaN,NaN,NaN,500.0,500.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.500,NaN

<h1>Scaling</h1>

In [83]:
from sklearn.preprocessing import RobustScaler
transformer = RobustScaler().fit(dataframe)
df_scaled=transformer.transform(dataframe)
df_scaled=pd.DataFrame(df_scaled)
column = dataframe.columns
df_scaled.columns = column
df_scaled.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Specialist surgical workforce (per 100,000 population)","Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population)
0,NaN,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,NaN,-8.328502,NaN,...,-0.2875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.919919,NaN
1,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.917543,NaN
2,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.915141,NaN
3,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,-8.144928,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.912738,NaN
4,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.908900,NaN

In [86]:
df_scaled['Country Name']=list(df['Country Name'])
df_scaled['Year']=list(df['Year'])
df_scaled['Label']=list(df['Label'])
df_scaled.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,NaN,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,NaN,-8.328502,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.919919,NaN,Afghanistan,2000,1.0
1,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.917543,NaN,Afghanistan,2001,1.0
2,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.915141,NaN,Afghanistan,2002,1.0
3,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,-8.144928,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.912738,NaN,Afghanistan,2003,1.0
4,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.908900,NaN,Afghanistan,2004,0.0

<h1>1. Random All</h1>

In [6]:
df_1 = df_scaled
missing_column = df_1.columns[df_1.isna().any()].tolist()

In [15]:
np.setdiff1d(df_1.columns.values.tolist(), missing_column)

array([], dtype='<U127')

In [21]:
def random_imputation(dft, feature):
    number_missing = dft[feature].isnull().sum()
    observed_value = dft.loc[dft[feature].notnull(), feature]
    dft.loc[dft[feature].isnull(), feature] = np.random.choice(observed_value, number_missing, replace = True)
    #dft.loc[dft[feature].isnull(), feature] = np.random.choice(observed_value, number_missing, replace = True)
    return dft

In [22]:
for feature in missing_column:
    df_1 = random_imputation(df_1, feature)

In [26]:
df_1['Country Name']=list(df['Country Name'])
df_1['Year']=list(df['Year'])
df_1['Label']=list(df['Label'])
df_1.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.038077,0.655136,-0.204790,-0.434317,-0.179372,-0.183099,-0.155835,0.441696,-8.328502,0.653091,...,-0.463647,-0.968529,1.143261,-0.481481,1.311037,-0.919919,-0.301241,Afghanistan,2000,1.0
1,0.038077,-0.042633,0.024415,-0.377322,-0.179372,-0.183099,-0.171660,0.392226,0.115942,1.183278,...,0.903648,-0.087378,1.160747,-0.333333,-0.260870,-0.917543,-1.562517,Afghanistan,2001,1.0
2,0.014229,1.200487,-0.051006,0.429660,-0.179372,-0.183099,-0.113158,1.215548,-0.463768,-0.038878,...,-0.496645,-0.774922,-0.268294,-1.037037,0.541806,-0.915141,0.390180,Afghanistan,2002,1.0
3,-0.030592,1.734499,1.136500,-0.290628,-0.179372,-0.183099,5.572335,0.282686,-8.144928,-0.410668,...,0.552072,0.086739,-0.417725,0.074074,-0.133779,-0.912738,0.214218,Afghanistan,2003,1.0
4,-0.478188,-1.411882,-1.010730,0.375818,-0.179372,-0.183099,0.020718,-0.424028,-0.599034,1.236786,...,0.859794,-0.643961,-0.446326,0.296296,0.107023,-0.908900,1.447990,Afghanistan,2004,0.0

In [28]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_1['Country Name'] = le.fit_transform(df_1['Country Name'])
df_1['Country Name']

0         0
1         0
2         0
3         0
4         0
       ...
4275    203
4276    203
4277    203
4278    203
4279    203
Name: Country Name, Length: 4280, dtype: int64

In [34]:
df_1.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Specialist surgical workforce (per 100,000 population)","Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population)
0,0.038077,0.655136,-0.204790,-0.434317,-0.179372,-0.183099,-0.155835,0.441696,-8.328502,0.653091,...,-0.2875,-0.087719,0.800000,-0.463647,-0.968529,1.143261,-0.481481,1.311037,-0.919919,-0.301241
1,0.038077,-0.042633,0.024415,-0.377322,-0.179372,-0.183099,-0.171660,0.392226,0.115942,1.183278,...,0.8375,1.355890,-0.771429,0.903648,-0.087378,1.160747,-0.333333,-0.260870,-0.917543,-1.562517
2,0.014229,1.200487,-0.051006,0.429660,-0.179372,-0.183099,-0.113158,1.215548,-0.463768,-0.038878,...,-0.0250,0.087719,0.014286,-0.496645,-0.774922,-0.268294,-1.037037,0.541806,-0.915141,0.390180
3,-0.030592,1.734499,1.136500,-0.290628,-0.179372,-0.183099,5.572335,0.282686,-8.144928,-0.410668,...,0.0750,4.914787,0.585714,0.552072,0.086739,-0.417725,0.074074,-0.133779,-0.912738,0.214218
4,-0.478188,-1.411882,-1.010730,0.375818,-0.179372,-0.183099,0.020718,-0.424028,-0.599034,1.236786,...,2.3375,0.303258,-0.800000,0.859794,-0.643961,-0.446326,0.296296,0.107023,-0.908900,1.447990

In [29]:
df_1.to_csv("Random_All.csv")

<h1>2. Random All with Normalization</h1>

In [38]:
df_2 = df_1
#df_2.drop(['Country Name', 'Year', 'Label'], axis = 1, inplace = True)
df_2.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Specialist surgical workforce (per 100,000 population)","Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population)
0,0.038077,0.655136,-0.204790,-0.434317,-0.179372,-0.183099,-0.155835,0.441696,-8.328502,0.653091,...,-0.2875,-0.087719,0.800000,-0.463647,-0.968529,1.143261,-0.481481,1.311037,-0.919919,-0.301241
1,0.038077,-0.042633,0.024415,-0.377322,-0.179372,-0.183099,-0.171660,0.392226,0.115942,1.183278,...,0.8375,1.355890,-0.771429,0.903648,-0.087378,1.160747,-0.333333,-0.260870,-0.917543,-1.562517
2,0.014229,1.200487,-0.051006,0.429660,-0.179372,-0.183099,-0.113158,1.215548,-0.463768,-0.038878,...,-0.0250,0.087719,0.014286,-0.496645,-0.774922,-0.268294,-1.037037,0.541806,-0.915141,0.390180
3,-0.030592,1.734499,1.136500,-0.290628,-0.179372,-0.183099,5.572335,0.282686,-8.144928,-0.410668,...,0.0750,4.914787,0.585714,0.552072,0.086739,-0.417725,0.074074,-0.133779,-0.912738,0.214218
4,-0.478188,-1.411882,-1.010730,0.375818,-0.179372,-0.183099,0.020718,-0.424028,-0.599034,1.236786,...,2.3375,0.303258,-0.800000,0.859794,-0.643961,-0.446326,0.296296,0.107023,-0.908900,1.447990

In [40]:
#Normalise Random All data
from sklearn.preprocessing import Normalizer
transformer = Normalizer().fit(df_2)
df_2=transformer.transform(df_2)
df_2=pd.DataFrame(df_2, columns = df_1.columns.values.tolist())
df_2.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Specialist surgical workforce (per 100,000 population)","Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population)
0,0.000123,0.002115,-0.000661,-0.001402,-0.000579,-0.000591,-0.000503,0.001426,-0.026888,0.002108,...,-0.000928,-0.000283,0.002583,-0.001497,-0.003127,0.003691,-0.001554,0.004233,-0.002970,-0.000973
1,0.000116,-0.000130,0.000074,-0.001148,-0.000546,-0.000557,-0.000522,0.001193,0.000353,0.003600,...,0.002548,0.004125,-0.002347,0.002749,-0.000266,0.003531,-0.001014,-0.000794,-0.002791,-0.004754
2,0.000066,0.005536,-0.000235,0.001981,-0.000827,-0.000844,-0.000522,0.005605,-0.002138,-0.000179,...,-0.000115,0.000404,0.000066,-0.002290,-0.003573,-0.001237,-0.004782,0.002498,-0.004220,0.001799
3,-0.000165,0.009380,0.006146,-0.001572,-0.000970,-0.000990,0.030135,0.001529,-0.044048,-0.002221,...,0.000406,0.026579,0.003168,0.002986,0.000469,-0.002259,0.000401,-0.000723,-0.004936,0.001158
4,-0.002294,-0.006772,-0.004848,0.001803,-0.000860,-0.000878,0.000099,-0.002034,-0.002873,0.005932,...,0.011211,0.001455,-0.003837,0.004124,-0.003089,-0.002141,0.001421,0.000513,-0.004359,0.006945

In [41]:
df_2['Country Name']=list(df['Country Name'])
df_2['Year']=list(df['Year'])
df_2['Label']=list(df['Label'])
#df_2.columns = df.columns
df_2.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.000123,0.002115,-0.000661,-0.001402,-0.000579,-0.000591,-0.000503,0.001426,-0.026888,0.002108,...,-0.001497,-0.003127,0.003691,-0.001554,0.004233,-0.002970,-0.000973,Afghanistan,2000,1.0
1,0.000116,-0.000130,0.000074,-0.001148,-0.000546,-0.000557,-0.000522,0.001193,0.000353,0.003600,...,0.002749,-0.000266,0.003531,-0.001014,-0.000794,-0.002791,-0.004754,Afghanistan,2001,1.0
2,0.000066,0.005536,-0.000235,0.001981,-0.000827,-0.000844,-0.000522,0.005605,-0.002138,-0.000179,...,-0.002290,-0.003573,-0.001237,-0.004782,0.002498,-0.004220,0.001799,Afghanistan,2002,1.0
3,-0.000165,0.009380,0.006146,-0.001572,-0.000970,-0.000990,0.030135,0.001529,-0.044048,-0.002221,...,0.002986,0.000469,-0.002259,0.000401,-0.000723,-0.004936,0.001158,Afghanistan,2003,1.0
4,-0.002294,-0.006772,-0.004848,0.001803,-0.000860,-0.000878,0.000099,-0.002034,-0.002873,0.005932,...,0.004124,-0.003089,-0.002141,0.001421,0.000513,-0.004359,0.006945,Afghanistan,2004,0.0

In [44]:
le = LabelEncoder()
df_2['Country Name'] = le.fit_transform(df_2['Country Name'])
df_2['Country Name']

0         0
1         0
2         0
3         0
4         0
       ...
4275    203
4276    203
4277    203
4278    203
4279    203
Name: Country Name, Length: 4280, dtype: int64

In [45]:
df_2.to_csv('Random_All_Norm.csv')

<h1>3. Random All SRI</h1>

In [50]:
df_3 = df_scaled
df_3.columns = df_scaled.columns
df_3.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Specialist surgical workforce (per 100,000 population)","Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population)
0,NaN,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,NaN,-8.328502,NaN,...,-0.2875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.919919,NaN
1,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.917543,NaN
2,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.915141,NaN
3,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,-8.144928,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.912738,NaN
4,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.908900,NaN

In [52]:
missing_column = df_3.columns[df_3.isna().any()].tolist()

array([], dtype='<U127')

In [55]:
def random_imputation(dft, feature):
    number_missing = dft[feature].isnull().sum()
    observed_value = dft.loc[dft[feature].notnull(), feature]
    dft.loc[dft[feature].isnull(), feature + '_imp'] = np.random.choice(observed_value, number_missing, replace = True)
    return dft

In [56]:
for feature in missing_column:
    df_3[feature + '_imp'] = df_3[feature]
    df_3 = random_imputation(df_3, feature)

In [59]:
#Stochastic Regression Imputation
from sklearn import linear_model
random_data = pd.DataFrame(columns = ["Ran" + name for name in missing_column])

for feature in missing_column:
    #print('feature')
    yx = np.nan_to_num(df_3[feature + '_imp'])
    random_data["Ran" + feature] = df_3[feature + '_imp']
    parameters = list(set(df_3.columns) - set(missing_column) - {feature + '_imp'})
    t = np.nan_to_num(df_3[parameters])
    
    model = linear_model.LinearRegression()
    model.fit(X = t, y = yx)
    
    predict = model.predict(t)
    std_error = (predict[df_3[feature].notnull()] - df_3.loc[df[feature].notnull(), feature + '_imp']).std()
    
    random_predict = np.random.normal(size = df_3[feature].shape[0], 
                                      loc = predict, 
                                      scale = std_error)
    random_data.loc[(df_3[feature].isnull()) & (random_predict > 0), "Ran" + feature] = random_predict[(df_3[feature].isnull()) & 
                                                                            (random_predict > 0)]

In [61]:
df_4 = pd.DataFrame(random_data, columns = random_data.columns)
df_4.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanSpecialist surgical workforce (per 100,000 population)","RanSuicide mortality rate (per 100,000 population)",RanTime required to build a warehouse (days),"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population)
0,-2.602389,3.985925,2.077762,1.212096,-0.179372,-0.183099,-0.155835,0.590011,-8.328502,0.494134,...,-0.287500,-0.398496,-0.342857,1.748792,-0.749114,1.135823,0.222222,1.294860,-0.919919,0.651027
1,-2.227133,-0.288810,3.886375,0.809056,-0.179372,-0.183099,-0.113158,-0.918728,0.077295,0.706113,...,0.474751,1.051742,0.545078,1.453885,1.203790,-0.388192,0.296296,0.204711,-0.917543,0.952344
2,0.018463,0.210614,-2.073679,0.066905,-0.179372,-0.183099,6.398268,0.118182,-0.009662,-0.200537,...,-0.312500,1.267376,-0.742857,1.667889,-0.569350,0.108709,-1.259259,0.122921,-0.915141,-0.324896
3,0.038077,2.591482,-0.338037,-0.324614,-0.179372,-0.183099,2.838861,0.496365,-8.144928,-0.430001,...,1.212266,0.991606,-0.828571,0.202481,-0.799923,0.688602,-1.037037,0.654862,-0.912738,-1.432244
4,-2.179914,2.161485,1.058747,0.457580,-0.179372,-0.183099,0.717249,0.249573,0.125604,-0.176326,...,-0.675000,0.928016,-0.628571,0.347445,-0.747901,0.226066,0.407407,1.293493,-0.908900,-0.284492

In [63]:
random_data['Country Name']=list(df['Country Name'])
random_data['Year']=list(df['Year'])
random_data['Label']=list(df['Label'])
#df_2.columns = df.columns
random_data.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population),Country Name,Year,Label
0,-2.602389,3.985925,2.077762,1.212096,-0.179372,-0.183099,-0.155835,0.590011,-8.328502,0.494134,...,1.748792,-0.749114,1.135823,0.222222,1.294860,-0.919919,0.651027,Afghanistan,2000,1.0
1,-2.227133,-0.288810,3.886375,0.809056,-0.179372,-0.183099,-0.113158,-0.918728,0.077295,0.706113,...,1.453885,1.203790,-0.388192,0.296296,0.204711,-0.917543,0.952344,Afghanistan,2001,1.0
2,0.018463,0.210614,-2.073679,0.066905,-0.179372,-0.183099,6.398268,0.118182,-0.009662,-0.200537,...,1.667889,-0.569350,0.108709,-1.259259,0.122921,-0.915141,-0.324896,Afghanistan,2002,1.0
3,0.038077,2.591482,-0.338037,-0.324614,-0.179372,-0.183099,2.838861,0.496365,-8.144928,-0.430001,...,0.202481,-0.799923,0.688602,-1.037037,0.654862,-0.912738,-1.432244,Afghanistan,2003,1.0
4,-2.179914,2.161485,1.058747,0.457580,-0.179372,-0.183099,0.717249,0.249573,0.125604,-0.176326,...,0.347445,-0.747901,0.226066,0.407407,1.293493,-0.908900,-0.284492,Afghanistan,2004,0.0

In [64]:
le = LabelEncoder()
random_data['Country Name'] = le.fit_transform(df_2['Country Name'])
random_data['Country Name']

0         0
1         0
2         0
3         0
4         0
       ...
4275    203
4276    203
4277    203
4278    203
4279    203
Name: Country Name, Length: 4280, dtype: int64

In [65]:
random_data.to_csv('SRI_All.csv')

In [72]:
random_data = pd.read_csv('SRI_All.csv')
random_data.head()

,Unnamed: 0,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),...,"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population),Country Name,Year,Label
0,0,-2.602389,3.985925,2.077762,1.212096,-0.179372,-0.183099,-0.155835,0.590011,-8.328502,...,1.748792,-0.749114,1.135823,0.222222,1.294860,-0.919919,0.651027,0,2000,1.0
1,1,-2.227133,-0.288810,3.886375,0.809056,-0.179372,-0.183099,-0.113158,-0.918728,0.077295,...,1.453885,1.203790,-0.388192,0.296296,0.204711,-0.917543,0.952344,0,2001,1.0
2,2,0.018463,0.210614,-2.073679,0.066905,-0.179372,-0.183099,6.398268,0.118182,-0.009662,...,1.667889,-0.569350,0.108709,-1.259259,0.122921,-0.915141,-0.324896,0,2002,1.0
3,3,0.038077,2.591482,-0.338037,-0.324614,-0.179372,-0.183099,2.838861,0.496365,-8.144928,...,0.202481,-0.799923,0.688602,-1.037037,0.654862,-0.912738,-1.432244,0,2003,1.0
4,4,-2.179914,2.161485,1.058747,0.457580,-0.179372,-0.183099,0.717249,0.249573,0.125604,...,0.347445,-0.747901,0.226066,0.407407,1.293493,-0.908900,-0.284492,0,2004,0.0

In [73]:
random_data.drop(['Unnamed: 0'], axis = 1, inplace = True)
trydf = random_data.drop(['Country Name', 'Year', 'Label'], axis = 1)

<h1>4. SRI All with Norm</h1>

In [71]:
df_4.head()
df_4.drop(['Country Name', 'Year', 'Label'], axis = 1, inplace = True)
#random_data.drop(['Country Name', 'Year', 'Label'], axis = 1, inplace = True)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [74]:
from sklearn.preprocessing import Normalizer
transformer = Normalizer().fit(df_4)
df_4=transformer.transform(df_4)
df_4=pd.DataFrame(df_4, columns = trydf.columns.values.tolist())
df_4.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanSpecialist surgical workforce (per 100,000 population)","RanSuicide mortality rate (per 100,000 population)",RanTime required to build a warehouse (days),"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population)
0,-0.008393,0.012855,0.006701,0.003909,-0.000578,-0.000591,-0.000503,0.001903,-0.026860,0.001594,...,-0.000927,-0.001285,-0.001106,0.005640,-0.002416,0.003663,0.000717,0.004176,-0.002967,0.002100
1,-0.006765,-0.000877,0.011806,0.002458,-0.000545,-0.000556,-0.000344,-0.002791,0.000235,0.002145,...,0.001442,0.003195,0.001656,0.004417,0.003657,-0.001179,0.000900,0.000622,-0.002787,0.002893
2,0.000085,0.000967,-0.009524,0.000307,-0.000824,-0.000841,0.029386,0.000543,-0.000044,-0.000921,...,-0.001435,0.005821,-0.003412,0.007660,-0.002615,0.000499,-0.005784,0.000565,-0.004203,-0.001492
3,0.000205,0.013980,-0.001824,-0.001751,-0.000968,-0.000988,0.015314,0.002678,-0.043938,-0.002320,...,0.006540,0.005349,-0.004470,0.001092,-0.004315,0.003715,-0.005594,0.003533,-0.004924,-0.007726
4,-0.010319,0.010232,0.005012,0.002166,-0.000849,-0.000867,0.003395,0.001181,0.000595,-0.000835,...,-0.003195,0.004393,-0.002975,0.001645,-0.003540,0.001070,0.001929,0.006123,-0.004302,-0.001347

In [75]:
df_4['Country Name']=list(random_data['Country Name'])
df_4['Year']=list(random_data['Year'])
df_4['Label']=list(random_data['Label'])
#df_2.columns = df.columns
df_4.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population),Country Name,Year,Label
0,-0.008393,0.012855,0.006701,0.003909,-0.000578,-0.000591,-0.000503,0.001903,-0.026860,0.001594,...,0.005640,-0.002416,0.003663,0.000717,0.004176,-0.002967,0.002100,0,2000,1.0
1,-0.006765,-0.000877,0.011806,0.002458,-0.000545,-0.000556,-0.000344,-0.002791,0.000235,0.002145,...,0.004417,0.003657,-0.001179,0.000900,0.000622,-0.002787,0.002893,0,2001,1.0
2,0.000085,0.000967,-0.009524,0.000307,-0.000824,-0.000841,0.029386,0.000543,-0.000044,-0.000921,...,0.007660,-0.002615,0.000499,-0.005784,0.000565,-0.004203,-0.001492,0,2002,1.0
3,0.000205,0.013980,-0.001824,-0.001751,-0.000968,-0.000988,0.015314,0.002678,-0.043938,-0.002320,...,0.001092,-0.004315,0.003715,-0.005594,0.003533,-0.004924,-0.007726,0,2003,1.0
4,-0.010319,0.010232,0.005012,0.002166,-0.000849,-0.000867,0.003395,0.001181,0.000595,-0.000835,...,0.001645,-0.003540,0.001070,0.001929,0.006123,-0.004302,-0.001347,0,2004,0.0

In [76]:
df_4.to_csv('SRI_All_Norm.csv')

<h1>5. Random Country</h1>

In [97]:
def random_imputation(dft, feature):
    number_missing = dft[feature].isnull().sum()
    observed_value = dft.loc[dft[feature].notnull(), feature]
    dft.loc[dft[feature].isnull(), feature] = np.random.choice(observed_value, number_missing, replace = True)
    #dft.loc[dft[feature].isnull(), feature] = np.random.choice(observed_value, number_missing, replace = True)
    return dft

In [98]:
df_afghan = df_scaled[df_scaled['Country Name'] == "Afghanistan"]
missing_column = df_afghan.columns[df_afghan.isna().any()].tolist()
for feature in df_afghan.columns.values:
    if df_afghan[feature].isnull().sum() == 0 :
        df_afghan[feature] = df_afghan[feature]
    elif df_afghan[feature].isnull().sum() == df_afghan.shape[0] :
        df_afghan[feature] = [np.nan] * df_afghan.shape[0]
    else:
        #df_afghan[feature] = df_afghan[feature]
        df_afghan = random_imputation(df_afghan, feature)
df_afghan.head()

/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.000950,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,0.088339,-8.328502,-0.481243,...,-0.621874,-0.680728,-0.811931,-1.259259,0.374582,-0.919919,0.390865,Afghanistan,2000,1.0
1,-2.183597,NaN,NaN,NaN,-0.179372,-0.183099,0.019976,0.088339,-8.144928,-0.479703,...,-0.621874,-0.592534,-0.970635,-1.259259,0.374582,-0.917543,-0.875149,Afghanistan,2001,1.0
2,-0.784231,NaN,NaN,NaN,-0.179372,-0.183099,0.019976,0.053004,-7.700483,-0.481647,...,-0.652375,-0.475170,-0.912007,-1.259259,0.374582,-0.915141,-1.213333,Afghanistan,2002,1.0
3,-0.853478,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,0.088339,-8.144928,-0.481333,...,-0.654316,-0.592534,-0.612092,-1.148148,0.374582,-0.912738,-1.213333,Afghanistan,2003,1.0
4,0.000950,NaN,NaN,NaN,-0.179372,-0.183099,0.053873,0.088339,-5.671498,-0.479381,...,-0.597531,-0.586207,-0.970635,-1.148148,0.374582,-0.908900,-0.875149,Afghanistan,2004,0.0

In [102]:
country = df_scaled['Country Name'].unique().tolist()
df_5 = pd.DataFrame(df_afghan, columns = df_afghan.columns)
df_5.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.000950,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,0.088339,-8.328502,-0.481243,...,-0.621874,-0.680728,-0.811931,-1.259259,0.374582,-0.919919,0.390865,Afghanistan,2000,1.0
1,-2.183597,NaN,NaN,NaN,-0.179372,-0.183099,0.019976,0.088339,-8.144928,-0.479703,...,-0.621874,-0.592534,-0.970635,-1.259259,0.374582,-0.917543,-0.875149,Afghanistan,2001,1.0
2,-0.784231,NaN,NaN,NaN,-0.179372,-0.183099,0.019976,0.053004,-7.700483,-0.481647,...,-0.652375,-0.475170,-0.912007,-1.259259,0.374582,-0.915141,-1.213333,Afghanistan,2002,1.0
3,-0.853478,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,0.088339,-8.144928,-0.481333,...,-0.654316,-0.592534,-0.612092,-1.148148,0.374582,-0.912738,-1.213333,Afghanistan,2003,1.0
4,0.000950,NaN,NaN,NaN,-0.179372,-0.183099,0.053873,0.088339,-5.671498,-0.479381,...,-0.597531,-0.586207,-0.970635,-1.148148,0.374582,-0.908900,-0.875149,Afghanistan,2004,0.0

In [103]:
for i in range(len(country)):
    print(country[i])
    df_afghan = df_scaled[df_scaled['Country Name'] == country[i]]
    #missing_column = df_afghan.columns[df_afghan.isna().any()].tolist()
    for feature in df_afghan.columns.values:
        if df_afghan[feature].isnull().sum() == 0 :
            df_afghan[feature] = df_afghan[feature]
        elif df_afghan[feature].isnull().sum() == df_afghan.shape[0] :
            df_afghan[feature] = [np.nan] * df_afghan.shape[0]
        else:
            #df_afghan[feature + '_imp'] = df_afghan[feature]
            df_afghan = random_imputation(df_afghan, feature)
            #print(df_afghan.head())
    df_5 = df_5.append(df_afghan)

Afghanistan

/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

Angola
Australia
Bangladesh
Bermuda
Botswana
Brunei Darussalam
Cabo Verde
Central African Republic
China
Costa Rica
Cyprus
Dominican Republic
Equatorial Guinea
Faroe Islands
Gabon
Greece
Guinea-Bissau
Albania
Antigua and Barbuda
Austria
Barbados
Bhutan
Brazil
Bulgaria
Cambodia
Chad
Colombia
Cote d'Ivoire
Czech Republic
Ecuador
Eritrea
Fiji
Gambia, The
Greenland
Guyana
Algeria
Argentina
Azerbaijan
Belarus
Bolivia
British Virgin Islands
Burkina Faso
Cameroon
Channel Islands
Comoros
Croatia
Denmark
Egypt, Arab Rep.
Estonia
Finland
Grenada
Haiti
American Samoa
Armenia
Bahamas, The
Belgium
Bosnia and Herzegovina
Burundi
Canada
Chile
Cuba
Djibouti
Eswatini
France
Georgia
Guam
Honduras
Andorra
Aruba
Belize
Cayman Islands
Curacao
Dominica
El Salvador
Ethiopia
French Polynesia
Germany
Guatemala
Bahrain
Benin
Congo, Dem. Rep.
Ghana
Guinea
Gibraltar
Hong Kong SAR, China
Hungary
Iceland
India
Indonesia
Iran, Islamic Rep.
Iraq
Ireland
Isle of Man
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, Dem. Peopleâ€™s Rep.
Korea, Rep.
Kosovo
Kuwait
Kyrgyz Republic
Lao PDR
Latvia
Lebanon
Lesotho
Liberia
Libya
Lithuania
Luxembourg
Macao SAR, China
Madagascar
Malawi
Malaysia
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Moldova
Monaco
Mongolia
Morocco
Mozambique
Myanmar
Namibia
Nauru
Netherlands
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Northern Mariana Islands
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Puerto Rico
Qatar
Romania
Russian Federation
Rwanda
Samoa
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovak Republic
Slovenia
Somalia
South Africa
South Sudan
Spain
Sri Lanka
St. Lucia
St. Martin (French part)
St. Vincent and the Grenadines
Sudan
Suriname
Sweden
Switzerland
Syrian Arab Republic
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Vietnam
West Bank and Gaza
Yemen, Rep.
Zambia
Zimbabwe

In [108]:
missing_column = df_5.columns[df_5.isna().any()].tolist()
for feature in missing_column:
    #print(feature)
    #df_3[feature] = df_3[feature]
    df_5 = random_imputation(df_5, feature)
df_5.isnull().sum()

ARI treatment (% of children under 5 taken to a health provider)    0
Access to electricity (% of population)                             0
Adjusted net national income (annual % growth)                      0
Adjusted net national income per capita (annual % growth)           0
Adolescents out of school (% of lower secondary school age)         0
                                                                   ..
Unmet need for contraception (% of married women ages 15-49)        0
Urban population (% of total population)                            0
Country Name                                                        0
Year                                                                0
Label                                                               0
Length: 139, dtype: int64

In [109]:
df_5.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.000950,-1.152598,-4.601683,2.533685,-0.179372,-0.183099,-0.155835,0.088339,-8.328502,-0.481243,...,-0.621874,-0.680728,-0.811931,-1.259259,0.374582,-0.919919,0.390865,Afghanistan,2000,1.0
1,-2.183597,0.420720,-0.462149,-0.446293,-0.179372,-0.183099,0.019976,0.088339,-8.144928,-0.479703,...,-0.621874,-0.592534,-0.970635,-1.259259,0.374582,-0.917543,-0.875149,Afghanistan,2001,1.0
2,-0.784231,-0.188912,-1.727325,-0.007234,-0.179372,-0.183099,0.019976,0.053004,-7.700483,-0.481647,...,-0.652375,-0.475170,-0.912007,-1.259259,0.374582,-0.915141,-1.213333,Afghanistan,2002,1.0
3,-0.853478,0.693807,-1.268966,0.745217,-0.179372,-0.183099,-0.155835,0.088339,-8.144928,-0.481333,...,-0.654316,-0.592534,-0.612092,-1.148148,0.374582,-0.912738,-1.213333,Afghanistan,2003,1.0
4,0.000950,1.264488,1.497863,-0.401654,-0.179372,-0.183099,0.053873,0.088339,-5.671498,-0.479381,...,-0.597531,-0.586207,-0.970635,-1.148148,0.374582,-0.908900,-0.875149,Afghanistan,2004,0.0

In [110]:
df_5.to_csv('Random_Country.csv')

<h1>6. Random Country with Normalisation</h1>

In [111]:
df_6 = pd.DataFrame(df_5, columns = df_5.columns)
df_6.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.000950,-1.152598,-4.601683,2.533685,-0.179372,-0.183099,-0.155835,0.088339,-8.328502,-0.481243,...,-0.621874,-0.680728,-0.811931,-1.259259,0.374582,-0.919919,0.390865,Afghanistan,2000,1.0
1,-2.183597,0.420720,-0.462149,-0.446293,-0.179372,-0.183099,0.019976,0.088339,-8.144928,-0.479703,...,-0.621874,-0.592534,-0.970635,-1.259259,0.374582,-0.917543,-0.875149,Afghanistan,2001,1.0
2,-0.784231,-0.188912,-1.727325,-0.007234,-0.179372,-0.183099,0.019976,0.053004,-7.700483,-0.481647,...,-0.652375,-0.475170,-0.912007,-1.259259,0.374582,-0.915141,-1.213333,Afghanistan,2002,1.0
3,-0.853478,0.693807,-1.268966,0.745217,-0.179372,-0.183099,-0.155835,0.088339,-8.144928,-0.481333,...,-0.654316,-0.592534,-0.612092,-1.148148,0.374582,-0.912738,-1.213333,Afghanistan,2003,1.0
4,0.000950,1.264488,1.497863,-0.401654,-0.179372,-0.183099,0.053873,0.088339,-5.671498,-0.479381,...,-0.597531,-0.586207,-0.970635,-1.148148,0.374582,-0.908900,-0.875149,Afghanistan,2004,0.0

In [112]:
df_6.drop(['Country Name', 'Year', 'Label'], axis = 1, inplace = True)
df_5.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.000950,-1.152598,-4.601683,2.533685,-0.179372,-0.183099,-0.155835,0.088339,-8.328502,-0.481243,...,-0.621874,-0.680728,-0.811931,-1.259259,0.374582,-0.919919,0.390865,Afghanistan,2000,1.0
1,-2.183597,0.420720,-0.462149,-0.446293,-0.179372,-0.183099,0.019976,0.088339,-8.144928,-0.479703,...,-0.621874,-0.592534,-0.970635,-1.259259,0.374582,-0.917543,-0.875149,Afghanistan,2001,1.0
2,-0.784231,-0.188912,-1.727325,-0.007234,-0.179372,-0.183099,0.019976,0.053004,-7.700483,-0.481647,...,-0.652375,-0.475170,-0.912007,-1.259259,0.374582,-0.915141,-1.213333,Afghanistan,2002,1.0
3,-0.853478,0.693807,-1.268966,0.745217,-0.179372,-0.183099,-0.155835,0.088339,-8.144928,-0.481333,...,-0.654316,-0.592534,-0.612092,-1.148148,0.374582,-0.912738,-1.213333,Afghanistan,2003,1.0
4,0.000950,1.264488,1.497863,-0.401654,-0.179372,-0.183099,0.053873,0.088339,-5.671498,-0.479381,...,-0.597531,-0.586207,-0.970635,-1.148148,0.374582,-0.908900,-0.875149,Afghanistan,2004,0.0

In [114]:
column = df_6.columns.values.tolist()

In [115]:
transformer = Normalizer().fit(df_6)
df_6=transformer.transform(df_6)
df_6=pd.DataFrame(df_6, columns = column)
df_6.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Specialist surgical workforce (per 100,000 population)","Suicide mortality rate (per 100,000 population)",Time required to build a warehouse (days),"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population)
0,0.000003,-0.003721,-0.014856,0.008180,-0.000579,-0.000591,-0.000503,0.000285,-0.026888,-0.001554,...,-0.000928,0.001206,-0.002813,-0.002008,-0.002198,-0.002621,-0.004065,0.001209,-0.002970,0.001262
1,-0.006638,0.001279,-0.001405,-0.001357,-0.000545,-0.000557,0.000061,0.000269,-0.024762,-0.001458,...,-0.001254,0.001135,-0.002649,-0.001891,-0.001801,-0.002951,-0.003828,0.001139,-0.002789,-0.002661
2,-0.003613,-0.000870,-0.007958,-0.000033,-0.000826,-0.000844,0.000092,0.000244,-0.035477,-0.002219,...,-0.001843,0.001720,-0.004015,-0.003006,-0.002189,-0.004202,-0.005802,0.001726,-0.004216,-0.005590
3,-0.004617,0.003754,-0.006865,0.004032,-0.000970,-0.000991,-0.000843,0.000478,-0.044065,-0.002604,...,-0.002164,0.010644,-0.004715,-0.003540,-0.003206,-0.003312,-0.006212,0.002027,-0.004938,-0.006564
4,0.000005,0.006059,0.007178,-0.001925,-0.000860,-0.000877,0.000258,0.000423,-0.027177,-0.002297,...,-0.001977,0.009428,-0.004176,-0.002863,-0.002809,-0.004651,-0.005502,0.001795,-0.004355,-0.004194

In [116]:
df_6['Country Name']=list(df_5['Country Name'])
df_6['Year']=list(df_5['Year'])
df_6['Label']=list(df_5['Label'])
#df_2.columns = df.columns
df_6.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",Total debt service (% of GNI),Trade (% of GDP),Travel services (% of commercial service exports),UHC service coverage index,Unmet need for contraception (% of married women ages 15-49),Urban population (% of total population),Country Name,Year,Label
0,0.000003,-0.003721,-0.014856,0.008180,-0.000579,-0.000591,-0.000503,0.000285,-0.026888,-0.001554,...,-0.002008,-0.002198,-0.002621,-0.004065,0.001209,-0.002970,0.001262,Afghanistan,2000,1.0
1,-0.006638,0.001279,-0.001405,-0.001357,-0.000545,-0.000557,0.000061,0.000269,-0.024762,-0.001458,...,-0.001891,-0.001801,-0.002951,-0.003828,0.001139,-0.002789,-0.002661,Afghanistan,2001,1.0
2,-0.003613,-0.000870,-0.007958,-0.000033,-0.000826,-0.000844,0.000092,0.000244,-0.035477,-0.002219,...,-0.003006,-0.002189,-0.004202,-0.005802,0.001726,-0.004216,-0.005590,Afghanistan,2002,1.0
3,-0.004617,0.003754,-0.006865,0.004032,-0.000970,-0.000991,-0.000843,0.000478,-0.044065,-0.002604,...,-0.003540,-0.003206,-0.003312,-0.006212,0.002027,-0.004938,-0.006564,Afghanistan,2003,1.0
4,0.000005,0.006059,0.007178,-0.001925,-0.000860,-0.000877,0.000258,0.000423,-0.027177,-0.002297,...,-0.002863,-0.002809,-0.004651,-0.005502,0.001795,-0.004355,-0.004194,Afghanistan,2004,0.0

In [117]:
le = LabelEncoder()
df_6['Country Name'] = le.fit_transform(df_6['Country Name'])
df_6['Country Name']

0         0
1         0
2         0
3         0
4         0
       ...
4295    203
4296    203
4297    203
4298    203
4299    203
Name: Country Name, Length: 4300, dtype: int64

In [118]:
df_6.to_csv('Random_Country_Norm.csv')

<h1>7. SRI Country</h1>

In [122]:
def random_imputation(dft, feature):
    number_missing = dft[feature].isnull().sum()
    observed_value = dft.loc[dft[feature].notnull(), feature]
    dft.loc[dft[feature].isnull(), feature] = np.random.choice(observed_value, number_missing, replace = True)
    return dft

In [129]:
df_afghan = df_scaled[df_scaled['Country Name'] == "Afghanistan"]
missing_column = df_afghan.columns[df_afghan.isna().any()].tolist()
for feature in df_afghan.columns.values:
    if df_afghan[feature].isnull().sum() == 0 :
        df_afghan[feature + '_imp'] = df_afghan[feature]
    elif df_afghan[feature].isnull().sum() == df_afghan.shape[0] :
        df_afghan[feature + '_imp'] = [np.nan] * df_afghan.shape[0]
    else:
        df_afghan[feature + '_imp'] = df_afghan[feature]
        df_afghan = random_imputation(df_afghan, feature)
df_afghan.head()

/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)_imp",Total debt service (% of GNI)_imp,Trade (% of GDP)_imp,Travel services (% of commercial service exports)_imp,UHC service coverage index_imp,Unmet need for contraception (% of married women ages 15-49)_imp,Urban population (% of total population)_imp,Country Name_imp,Year_imp,Label_imp
0,NaN,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,NaN,-8.328502,NaN,...,-0.597524,-0.591790,-0.747960,-1.148148,0.374582,-0.919919,0.390865,Afghanistan,2000,1.0
1,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,-0.597524,-0.374418,-0.935068,-1.259259,0.374582,-0.917543,0.390865,Afghanistan,2001,1.0
2,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,-0.597531,-0.374418,-0.769546,-1.148148,0.374582,-0.915141,-1.213333,Afghanistan,2002,1.0
3,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,-8.144928,NaN,...,-0.656074,-0.586207,-0.612092,-1.148148,0.374582,-0.912738,-1.213333,Afghanistan,2003,1.0
4,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,-0.654316,-0.374418,-0.941687,-1.148148,0.374582,-0.908900,-0.875149,Afghanistan,2004,0.0

In [130]:
country = df_scaled['Country Name'].unique().tolist()
df_7 = pd.DataFrame(df_afghan, columns = df_afghan.columns)
df_7.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)_imp",Total debt service (% of GNI)_imp,Trade (% of GDP)_imp,Travel services (% of commercial service exports)_imp,UHC service coverage index_imp,Unmet need for contraception (% of married women ages 15-49)_imp,Urban population (% of total population)_imp,Country Name_imp,Year_imp,Label_imp
0,NaN,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,NaN,-8.328502,NaN,...,-0.597524,-0.591790,-0.747960,-1.148148,0.374582,-0.919919,0.390865,Afghanistan,2000,1.0
1,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,-0.597524,-0.374418,-0.935068,-1.259259,0.374582,-0.917543,0.390865,Afghanistan,2001,1.0
2,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,-0.597531,-0.374418,-0.769546,-1.148148,0.374582,-0.915141,-1.213333,Afghanistan,2002,1.0
3,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,-8.144928,NaN,...,-0.656074,-0.586207,-0.612092,-1.148148,0.374582,-0.912738,-1.213333,Afghanistan,2003,1.0
4,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,-0.654316,-0.374418,-0.941687,-1.148148,0.374582,-0.908900,-0.875149,Afghanistan,2004,0.0

In [131]:
for i in range(len(country)):
    print(country[i])
    df_afghan = df_scaled[df_scaled['Country Name'] == country[i]]
    #missing_column = df_afghan.columns[df_afghan.isna().any()].tolist()
    for feature in df_afghan.columns.values:
        if df_afghan[feature].isnull().sum() == 0 :
            df_afghan[feature + '_imp'] = df_afghan[feature]
        elif df_afghan[feature].isnull().sum() == df_afghan.shape[0] :
            df_afghan[feature + '_imp'] = [np.nan] * df_afghan.shape[0]
        else:
            df_afghan[feature + '_imp'] = df_afghan[feature]
            df_afghan = random_imputation(df_afghan, feature)
            #print(df_afghan.head())
    df_7 = df_7.append(df_afghan)

Afghanistan

/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/saloniparekh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

Angola
Australia
Bangladesh
Bermuda
Botswana
Brunei Darussalam
Cabo Verde
Central African Republic
China
Costa Rica
Cyprus
Dominican Republic
Equatorial Guinea
Faroe Islands
Gabon
Greece
Guinea-Bissau
Albania
Antigua and Barbuda
Austria
Barbados
Bhutan
Brazil
Bulgaria
Cambodia
Chad
Colombia
Cote d'Ivoire
Czech Republic
Ecuador
Eritrea
Fiji
Gambia, The
Greenland
Guyana
Algeria
Argentina
Azerbaijan
Belarus
Bolivia
British Virgin Islands
Burkina Faso
Cameroon
Channel Islands
Comoros
Croatia
Denmark
Egypt, Arab Rep.
Estonia
Finland
Grenada
Haiti
American Samoa
Armenia
Bahamas, The
Belgium
Bosnia and Herzegovina
Burundi
Canada
Chile
Cuba
Djibouti
Eswatini
France
Georgia
Guam
Honduras
Andorra
Aruba
Belize
Cayman Islands
Curacao
Dominica
El Salvador
Ethiopia
French Polynesia
Germany
Guatemala
Bahrain
Benin
Congo, Dem. Rep.
Ghana
Guinea
Gibraltar
Hong Kong SAR, China
Hungary
Iceland
India
Indonesia
Iran, Islamic Rep.
Iraq
Ireland
Isle of Man
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, Dem. Peopleâ€™s Rep.
Korea, Rep.
Kosovo
Kuwait
Kyrgyz Republic
Lao PDR
Latvia
Lebanon
Lesotho
Liberia
Libya
Lithuania
Luxembourg
Macao SAR, China
Madagascar
Malawi
Malaysia
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Moldova
Monaco
Mongolia
Morocco
Mozambique
Myanmar
Namibia
Nauru
Netherlands
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Northern Mariana Islands
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Puerto Rico
Qatar
Romania
Russian Federation
Rwanda
Samoa
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovak Republic
Slovenia
Somalia
South Africa
South Sudan
Spain
Sri Lanka
St. Lucia
St. Martin (French part)
St. Vincent and the Grenadines
Sudan
Suriname
Sweden
Switzerland
Syrian Arab Republic
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Vietnam
West Bank and Gaza
Yemen, Rep.
Zambia
Zimbabwe

In [133]:
df_7.shape

(4300, 278)

In [134]:
missing_column = df_7.columns[df_7.isna().any()].tolist()
for feature in missing_column:
    #print(feature)
    #df_3[feature] = df_3[feature]
    df_7 = random_imputation(df_7, feature)

In [156]:
missing_column = df_7.columns[df_7.isna().any()].tolist()

In [135]:
pd.set_option('display.max_rows', df_7.shape[0])

In [149]:
df_7.drop(df_7.iloc[:,275:], axis = 1, inplace = True)

In [151]:
cname = df_7.pop('Country Name')
year = df_7.pop('Year')
abel = df_7.pop('Label')

In [152]:
df_7['Country Name']=cname
df_7['Year']=year
df_7['Label']=abel
#df_2.columns = df.columns
df_7.head()

,ARI treatment (% of children under 5 taken to a health provider),Access to electricity (% of population),Adjusted net national income (annual % growth),Adjusted net national income per capita (annual % growth),Adolescents out of school (% of lower secondary school age),Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) newly infected with HIV,"Air transport, passengers carried",Births attended by skilled health staff (% of total),"Borrowers from commercial banks (per 1,000 adults)",...,"Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)_imp",Total debt service (% of GNI)_imp,Trade (% of GDP)_imp,Travel services (% of commercial service exports)_imp,UHC service coverage index_imp,Unmet need for contraception (% of married women ages 15-49)_imp,Urban population (% of total population)_imp,Country Name,Year,Label
0,NaN,NaN,NaN,NaN,-0.179372,-0.183099,-0.155835,NaN,-8.328502,NaN,...,0.134550,-0.131145,-0.453601,0.074074,-0.802676,-0.919919,-0.187830,Afghanistan,2000,1.0
1,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,3.122264,-0.400366,-0.232684,-0.592593,0.026756,-0.917543,0.426939,Afghanistan,2001,1.0
2,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,0.250092,-0.429320,-0.566652,-1.481481,-0.113712,-0.915141,0.086864,Afghanistan,2002,1.0
3,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,-8.144928,NaN,...,0.183283,-0.464447,-0.410519,0.259259,0.200669,-0.912738,-1.005773,Afghanistan,2003,1.0
4,NaN,NaN,NaN,NaN,-0.179372,-0.183099,NaN,NaN,NaN,NaN,...,0.104840,0.707205,-0.615805,0.037037,0.374582,-0.908900,-0.334103,Afghanistan,2004,0.0

In [153]:
le = LabelEncoder()
df_7['Country Name'] = le.fit_transform(df_7['Country Name'])
df_7['Country Name']

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        5
21        5
22        5
23        5
24        5
25        5
26        5
27        5
28        5
29        5
30        5
31        5
32        5
33        5
34        5
35        5
36        5
37        5
38        5
39        5
40       10
41       10
42       10
43       10
44       10
45       10
46       10
47       10
48       10
49       10
50       10
51       10
52       10
53       10
54       10
55       10
56       10
57       10
58       10
59       10
60       15
61       15
62       15
63       15
64       15
65       15
66       15
67       15
68       15
69       15
70       15
71       15
72       15
73       15
74       15
75       15
76       15
77       15
78       15
79       15
80       21
81       21
82       21
83       21
84       21
85       21
86       21
87       21
88       21
89       21
90       21
91       21
92       21
93       21
94       21
95       21
96       21
97       21
98       21
99       21
100      25
101      25
102      25
103      25
104      25
105      25
106      25
107      25
108      25
109      25
110      25
111      25
112      25
113      25
114      25
115      25
116      25
117      25
118      25
119      25
120      28
121      28
122      28
123      28
124      28
125      28
126      28
127      28
128      28
129      28
130      28
131      28
132      28
133      28
134      28
135      28
136      28
137      28
138      28
139      28
140      32
141      32
142      32
143      32
144      32
145      32
146      32
147      32
148      32
149      32
150      32
151      32
152      32
153      32
154      32
155      32
156      32
157      32
158      32
159      32
160      37
161      37
162      37
163      37
164      37
165      37
166      37
167      37
168      37
169      37
170      37
171      37
172      37
173      37
174      37
175      37
176      37
177      37
178      37
179      37
180      41
181      41
182      41
183      41
184      41
185      41
186      41
187      41
188      41
189      41
190      41
191      41
192      41
193      41
194      41
195      41
196      41
197      41
198      41
199      41
200      45
201      45
202      45
203      45
204      45
205      45
206      45
207      45
208      45
209      45
210      45
211      45
212      45
213      45
214      45
215      45
216      45
217      45
218      45
219      45
220      50
221      50
222      50
223      50
224      50
225      50
226      50
227      50
228      50
229      50
230      50
231      50
232      50
233      50
234      50
235      50
236      50
237      50
238      50
239      50
240      55
241      55
242      55
243      55
244      55
245      55
246      55
247      55
248      55
249      55
250      55
251      55
252      55
253      55
254      55
255      55
256      55
257      55
258      55
259      55
260      59
261      59
262      59
263      59
264      59
265      59
266      59
267      59
268      59
269      59
270      59
271      59
272      59
273      59
274      59
275      59
276      59
277      59
278      59
279      59
280      64
281      64
282      64
283      64
284      64
285      64
286      64
287      64
288      64
289      64
290      64
291      64
292      64
293      64
294      64
295      64
296      64
297      64
298      64
299      64
300      69
301      69
302      69
303      69
304      69
305      69
306      69
307      69
308      69
309      69
310      69
311      69
312      69
313      69
314      69
315      69
316      69
317      69
318      69
319      69
320      75
321      75
322      75
323      75
324      75
325      75
326      75
327      75
328      75
329      75
330      75
331      75
332      75
333      75
334      75
335      75
336      75
337      75
338      75
339      75
1700     75
1701     75
1702     75
1703     75
1704     75
1705     75
1706     75
1707     75
1708     75
1709     75
1710     75
1711     75
1712     75
1713     75
1714     75
1715     75
1716     75
1717     75
1718     75
1719     75
340      81
341      81
342      81
343      81
344      81
345      81
346      81
347      81
348      81
349      81
350      81
351      81
352      81
353      81
354      81
355      81
356      81
357      81
358      81
359      81
1820     81
1821     81
1822     81
1823     81
1824     81
1825     81
1826     81
1827     81
1828     81
1829     81
1830     81
1831     81
1832     81
1833     81
1834     81
1835     81
1836     81
1837     81
1838     81
1839     81
360       1
361       1
362       1
363       1
364       1
365       1
366       1
367       1
368       1
369       1
370       1
371       1
372       1
373       1
374       1
375       1
376       1
377       1
378       1
379       1
380       6
381       6
382       6
383       6
384       6
385       6
386       6
387       6
388       6
389       6
390       6
391       6
392       6
393       6
394       6
395       6
396       6
397       6
398       6
399       6
400      11
401      11
402      11
403      11
404      11
405      11
406      11
407      11
408      11
409      11
410      11
411      11
412      11
413      11
414      11
415      11
416      11
417      11
418      11
419      11
420      16
421      16
422      16
423      16
424      16
425      16
426      16
427      16
428      16
429      16
430      16
431      16
432      16
433      16
434      16
435      16
436      16
437      16
438      16
439      16
440      22
441      22
442      22
443      22
444      22
445      22
446      22
447      22
448      22
449      22
450      22
451      22
452      22
453      22
454      22
455      22
456      22
457      22
458      22
459      22
460      26
461      26
462      26
463      26
464      26
465      26
466      26
467      26
468      26
469      26
470      26
471      26
472      26
473      26
474      26
475      26
476      26
477      26
478      26
479      26
480      29
481      29
482      29
483      29
484      29
485      29
486      29
487      29
488      29
489      29
490      29
491      29
492      29
493      29
494      29
495      29
496      29
497      29
498      29
499      29
500      33
501      33
502      33
503      33
504      33
505      33
506      33
507      33
508      33
509      33
510      33
511      33
512      33
513      33
514      33
515      33
516      33
517      33
518      33
519      33
520      38
521      38
522      38
523      38
524      38
525      38
526      38
527      38
528      38
529      38
530      38
531      38
532      38
533      38
534      38
535      38
536      38
537      38
538      38
539      38
540      42
541      42
542      42
543      42
544      42
545      42
546      42
547      42
548      42
549      42
550      42
551      42
552      42
553      42
554      42
555      42
556      42
557      42
558      42
559      42
560      46
561      46
562      46
563      46
564      46
565      46
566      46
567      46
568      46
569      46
570      46
571      46
572      46
573      46
574      46
575      46
576      46
577      46
578      46
579      46
580      51
581      51
582      51
583      51
584      51
585      51
586      51
587      51
588      51
589      51
590      51
591      51
592      51
593      51
594      51
595      51
596      51
597      51
598      51
599      51
600      56
601      56
602      56
603      56
604      56
605      56
606      56
607      56
608      56
609      56
610      56
611      56
612      56
613      56
614      56
615      56
616      56
617      56
618      56
619      56
620      60
621      60
622      60
623      60
624      60
625      60
626      60
627      60
628      60
629      60
630      60
631      60
632      60
633      60
634      60
635      60
636      60
637      60
638      60
639      60
640      65
641      65
642      65
643      65
644      65
645      65
646      65
647      65
648      65
649      65
650      65
651      65
652      65
653      65
654      65
655      65
656      65
657      65
658      65
659      65
660      70
661      70
662      70
663      70
664      70
665      70
666      70
667      70
668      70
669      70
670      70
671      70
672      70
673      70
674      70
675      70
676      70
677      70
678      70
679      70
680      76
681      76
682      76
683      76
684      76
685      76
686      76
687      76
688      76
689      76
690      76
691      76
692      76
693      76
694      76
695      76
696      76
697      76
698      76
699      76
1720     76
1721     76
1722     76
1723     76
1724     76
1725     76
1726     76
1727     76
1728     76
1729     76
1730     76
1731     76
1732     76
1733     76
1734     76
1735     76
1736     76
1737     76
1738     76
1739     76
700      82
701      82
702      82
703      82
704      82
705      82
706      82
707      82
708      82
709      82
710      82
711      82
712      82
713      82
714      82
715      82
716      82
717      82
718      82
719      82
1840     82
1841     82
1842     82
1843     82
1844     82
1845     82
1846     82
1847     82
1848     82
1849     82
1850     82
1851     82
1852     82
1853     82
1854     82
1855     82
1856     82
1857     82
1858     82
1859     82
720       2
721       2
722       2
723       2
724       2
725       2
726       2
727       2
728       2
729       2
730       2
731       2
732       2
733       2
734       2
735       2
736       2
737       2
738       2
739       2
740       7
741       7
742       7
743       7
744       7
745       7
746       7
747       7
748       7
749       7
750       7
751       7
752       7
753       7
754       7
755       7
756       7
757       7
758       7
759       7
760      12
761      12
762      12
763      12
764      12
765      12
766      12
767      12
768      12
769      12
770      12
771      12
772      12
773      12
774      12
775      12
776      12
777      12
778      12
779      12
780      17
781      17
782      17
783      17
784      17
785      17
786      17
787      17
788      17
789      17
790      17
791      17
792      17
793      17
794      17
795      17
796      17
797      17
798      17
799      17
800      23
801      23
802      23
803      23
804      23
805      23
806      23
807      23
808      23
809      23
810      23
811      23
812      23
813      23
814      23
815      23
816      23
817      23
818      23
819      23
820      27
821      27
822      27
823      27
824      27
825      27
826      27
827      27
828      27
829      27
830      27
831      27
832      27
833      27
834      27
835      27
836      27
837      27
838      27
839      27
840      30
841      30
842      30
843      30
844      30
845      30
846      30
847      30
848      30
849      30
850      30
851      30
852      30
853      30
854      30
855      30
856      30
857      30
858      30
859      30
860      34
861      34
862      34
863      34
864      34
865      34
866      34
867      34
868      34
869      34
870      34
871      34
872      34
873      34
874      34
875      34
876      34
877      34
878      34
879      34
880      39
881      39
882      39
883      39
884      39
885      39
886      39
887      39
888      39
889      39
890      39
891      39
892      39
893      39
894      39
895      39
896      39
897      39
898      39
899      39
900      43
901      43
902      43
903      43
904      43
905      43
906      43
907      43
908      43
909      43
910      43
911      43
912      43
913      43
914      43
915      43
916      43
917      43
918      43
919      43
920      47
921      47
922      47
923      47
924      47
925      47
926      47
927      47
928      47
929      47
930      47
931      47
932      47
933      47
934      47
935      47
936      47
937      47
938      47
939      47
940      52
941      52
942      52
943      52
944      52
945      52
946      52
947      52
948      52
949      52
950      52
951      52
952      52
953      52
954      52
955      52
956      52
957      52
958      52
959      52
960      57
961      57
962      57
963      57
964      57
965      57
966      57
967      57
968      57
969      57
970      57
971      57
972      57
973      57
974      57
975      57
976      57
977      57
978      57
979      57
980      61
981      61
982      61
983      61
984      61
985      61
986      61
987      61
988      61
989      61
990      61
991      61
992      61
993      61
994      61
995      61
996      61
997      61
998      61
999      61
1000     66
1001     66
1002     66
1003     66
1004     66
1005     66
1006     66
1007     66
1008     66
1009     66
1010     66
1011     66
1012     66
1013     66
1014     66
1015     66
1016     66
1017     66
1018     66
1019     66
1020     77
1021     77
1022     77
1023     77
1024     77
1025     77
1026     77
1027     77
1028     77
1029     77
1030     77
1031     77
1032     77
1033     77
1034     77
1035     77
1036     77
1037     77
1038     77
1039     77
1740     77
1741     77
1742     77
1743     77
1744     77
1745     77
1746     77
1747     77
1748     77
1749     77
1750     77
1751     77
1752     77
1753     77
1754     77
1755     77
1756     77
1757     77
1758     77
1759     77
1040     83
1041     83
1042     83
1043     83
1044     83
1045     83
1046     83
1047     83
1048     83
1049     83
1050     83
1051     83
1052     83
1053     83
1054     83
1055     83
1056     83
1057     83
1058     83
1059     83
1860     83
1861     83
1862     83
1863     83
1864     83
1865     83
1866     83
1867     83
1868     83
1869     83
1870     83
1871     83
1872     83
1873     83
1874     83
1875     83
1876     83
1877     83
1878     83
1879     83
1060      3
1061      3
1062      3
1063      3
1064      3
1065      3
1066      3
1067      3
1068      3
1069      3
1070      3
1071      3
1072      3
1073      3
1074      3
1075      3
1076      3
1077      3
1078      3
1079      3
1080      8
1081      8
1082      8
1083      8
1084      8
1085      8
1086      8
1087      8
1088      8
1089      8
1090      8
1091      8
1092      8
1093      8
1094      8
1095      8
1096      8
1097      8
1098      8
1099      8
1100     13
1101     13
1102     13
1103     13
1104     13
1105     13
1106     13
1107     13
1108     13
1109     13
1110     13
1111     13
1112     13
1113     13
1114     13
1115     13
1116     13
1117     13
1118     13
1119     13
1120     18
1121     18
1122     18
1123     18
1124     18
1125     18
1126     18
1127     18
1128     18
1129     18
1130     18
1131     18
1132     18
1133     18
1134     18
1135     18
1136     18
1137     18
1138     18
1139     18
1140     24
1141     24
1142     24
1143     24
1144     24
1145     24
1146     24
1147     24
1148     24
1149     24
1150     24
1151     24
1152     24
1153     24
1154     24
1155     24
1156     24
1157     24
1158     24
1159     24
1160     31
1161     31
1162     31
1163     31
1164     31
1165     31
1166     31
1167     31
1168     31
1169     31
1170     31
1171     31
1172     31
1173     31
1174     31
1175     31
1176     31
1177     31
1178     31
1179     31
1180     35
1181     35
1182     35
1183     35
1184     35
1185     35
1186     35
1187     35
1188     35
1189     35
1190     35
1191     35
1192     35
1193     35
1194     35
1195     35
1196     35
1197     35
1198     35
1199     35
1200     40
1201     40
1202     40
1203     40
1204     40
1205     40
1206     40
1207     40
1208     40
1209     40
1210     40
1211     40
1212     40
1213     40
1214     40
1215     40
1216     40
1217     40
1218     40
1219     40
1220     48
1221     48
1222     48
1223     48
1224     48
1225     48
1226     48
1227     48
1228     48
1229     48
1230     48
1231     48
1232     48
1233     48
1234     48
1235     48
1236     48
1237     48
1238     48
1239     48
1240     53
1241     53
1242     53
1243     53
1244     53
1245     53
1246     53
1247     53
1248     53
1249     53
1250     53
1251     53
1252     53
1253     53
1254     53
1255     53
1256     53
1257     53
1258     53
1259     53
1260     62
1261     62
1262     62
1263     62
1264     62
1265     62
1266     62
1267     62
1268     62
1269     62
1270     62
1271     62
1272     62
1273     62
1274     62
1275     62
1276     62
1277     62
1278     62
1279     62
1280     67
1281     67
1282     67
1283     67
1284     67
1285     67
1286     67
1287     67
1288     67
1289     67
1290     67
1291     67
1292     67
1293     67
1294     67
1295     67
1296     67
1297     67
1298     67
1299     67
1300     71
1301     71
1302     71
1303     71
1304     71
1305     71
1306     71
1307     71
1308     71
1309     71
1310     71
1311     71
1312     71
1313     71
1314     71
1315     71
1316     71
1317     71
1318     71
1319     71
1320     78
1321     78
1322     78
1323     78
1324     78
1325     78
1326     78
1327     78
1328     78
1329     78
1330     78
1331     78
1332     78
1333     78
1334     78
1335     78
1336     78
1337     78
1338     78
1339     78
1780     78
1781     78
1782     78
1783     78
1784     78
1785     78
1786     78
1787     78
1788     78
1789     78
1790     78
1791     78
1792     78
1793     78
1794     78
1795     78
1796     78
1797     78
1798     78
1799     78
1340     84
1341     84
1342     84
1343     84
1344     84
1345     84
1346     84
1347     84
1348     84
1349     84
1350     84
1351     84
1352     84
1353     84
1354     84
1355     84
1356     84
1357     84
1358     84
1359     84
1880     84
1881     84
1882     84
1883     84
1884     84
1885     84
1886     84
1887     84
1888     84
1889     84
1890     84
1891     84
1892     84
1893     84
1894     84
1895     84
1896     84
1897     84
1898     84
1899     84
1360      4
1361      4
1362      4
1363      4
1364      4
1365      4
1366      4
1367      4
1368      4
1369      4
1370      4
1371      4
1372      4
1373      4
1374      4
1375      4
1376      4
1377      4
1378      4
1379      4
1380      9
1381      9
1382      9
1383      9
1384      9
1385      9
1386      9
1387      9
1388      9
1389      9
1390      9
1391      9
1392      9
1393      9
1394      9
1395      9
1396      9
1397      9
1398      9
1399      9
1400     19
1401     19
1402     19
1403     19
1404     19
1405     19
1406     19
1407     19
1408     19
1409     19
1410     19
1411     19
1412     19
1413     19
1414     19
1415     19
1416     19
1417     19
1418     19
1419     19
1420     36
1421     36
1422     36
1423     36
1424     36
1425     36
1426     36
1427     36
1428     36
1429     36
1430     36
1431     36
1432     36
1433     36
1434     36
1435     36
1436     36
1437     36
1438     36
1439     36
1440     49
1441     49
1442     49
1443     49
1444     49
1445     49
1446     49
1447     49
1448     49
1449     49
1450     49
1451     49
1452     49
1453     49
1454     49
1455     49
1456     49
1457     49
1458     49
1459     49
1460     54
1461     54
1462     54
1463     54
1464     54
1465     54
1466     54
1467     54
1468     54
1469     54
1470     54
1471     54
1472     54
1473     54
1474     54
1475     54
1476     54
1477     54
1478     54
1479     54
1480     58
1481     58
1482     58
1483     58
1484     58
1485     58

In [157]:
#Stochastic Regression Imputation
from sklearn import linear_model
random_data = pd.DataFrame(columns = ["Ran" + name for name in missing_column])

for feature in missing_column:
    #print('feature')
    yx = np.nan_to_num(df_7[feature + '_imp'])
    random_data["Ran" + feature] = df_7[feature + '_imp']
    parameters = list(set(df_7.columns) - set(missing_column) - {feature + '_imp'})
    t = np.nan_to_num(df_7[parameters])
    
    model = linear_model.LinearRegression()
    model.fit(X = t, y = yx)
    
    predict = model.predict(t)
    std_error = (predict[df_7[feature].notnull()] - df_7.loc[df[feature].notnull(), feature + '_imp']).std()
    
    random_predict = np.random.normal(size = df_7[feature].shape[0], 
                                      loc = predict, 
                                      scale = std_error)
    random_data.loc[(df_7[feature].isnull()) & (random_predict > 0), "Ran" + feature] = random_predict[(df_7[feature].isnull()) & 
                                                                            (random_predict > 0)]

In [158]:
random_data.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanSpecialist surgical workforce (per 100,000 population)","RanSuicide mortality rate (per 100,000 population)",RanTime required to build a warehouse (days),"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population)
0,-2.280608,0.091388,-2.035433,3.320021,-0.179372,-0.183099,-0.155835,0.307420,-8.328502,0.562510,...,-0.287500,0.979164,-0.614286,0.380384,0.405094,0.224774,0.074074,0.460967,-0.919919,0.933944
1,-2.622162,2.733320,0.669289,1.355332,-0.179372,-0.183099,3.845733,-0.777385,0.106280,-0.318351,...,0.100000,0.573935,-0.871429,3.122264,-0.400366,-0.232684,-0.592593,0.972914,-0.917543,1.588362
2,0.038077,0.215125,0.075741,0.209425,-0.179372,-0.183099,4.342282,0.696113,0.019324,1.519854,...,1.367344,0.642114,0.370603,1.099635,-0.429320,0.203743,-1.481481,0.322559,-0.915141,0.086864
3,-0.055722,0.940383,1.595019,0.357377,-0.179372,-0.183099,2.755945,-1.024735,-8.144928,0.484245,...,0.209242,1.071538,0.267800,0.183283,0.025734,-0.410519,0.036473,0.200669,-0.912738,0.693920
4,0.028089,-4.366486,0.755514,0.661548,-0.179372,-0.183099,0.887984,0.494700,0.038647,-0.398757,...,-0.575000,-0.037594,0.147535,0.104840,0.707205,-0.615805,0.037037,0.395417,-0.908900,-0.334103

In [159]:
random_data.shape

(4300, 136)

In [162]:
df_8 = pd.DataFrame(random_data, columns = random_data.columns)
df_8.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanSpecialist surgical workforce (per 100,000 population)","RanSuicide mortality rate (per 100,000 population)",RanTime required to build a warehouse (days),"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population)
0,-2.280608,0.091388,-2.035433,3.320021,-0.179372,-0.183099,-0.155835,0.307420,-8.328502,0.562510,...,-0.287500,0.979164,-0.614286,0.380384,0.405094,0.224774,0.074074,0.460967,-0.919919,0.933944
1,-2.622162,2.733320,0.669289,1.355332,-0.179372,-0.183099,3.845733,-0.777385,0.106280,-0.318351,...,0.100000,0.573935,-0.871429,3.122264,-0.400366,-0.232684,-0.592593,0.972914,-0.917543,1.588362
2,0.038077,0.215125,0.075741,0.209425,-0.179372,-0.183099,4.342282,0.696113,0.019324,1.519854,...,1.367344,0.642114,0.370603,1.099635,-0.429320,0.203743,-1.481481,0.322559,-0.915141,0.086864
3,-0.055722,0.940383,1.595019,0.357377,-0.179372,-0.183099,2.755945,-1.024735,-8.144928,0.484245,...,0.209242,1.071538,0.267800,0.183283,0.025734,-0.410519,0.036473,0.200669,-0.912738,0.693920
4,0.028089,-4.366486,0.755514,0.661548,-0.179372,-0.183099,0.887984,0.494700,0.038647,-0.398757,...,-0.575000,-0.037594,0.147535,0.104840,0.707205,-0.615805,0.037037,0.395417,-0.908900,-0.334103

In [163]:
random_data['Country Name'] = list(df_7['Country Name'])
random_data['Year'] = list(df_7['Year'])
random_data['Label'] = list(df_7['Label'])
random_data.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population),Country Name,Year,Label
0,-2.280608,0.091388,-2.035433,3.320021,-0.179372,-0.183099,-0.155835,0.307420,-8.328502,0.562510,...,0.380384,0.405094,0.224774,0.074074,0.460967,-0.919919,0.933944,0,2000,1.0
1,-2.622162,2.733320,0.669289,1.355332,-0.179372,-0.183099,3.845733,-0.777385,0.106280,-0.318351,...,3.122264,-0.400366,-0.232684,-0.592593,0.972914,-0.917543,1.588362,0,2001,1.0
2,0.038077,0.215125,0.075741,0.209425,-0.179372,-0.183099,4.342282,0.696113,0.019324,1.519854,...,1.099635,-0.429320,0.203743,-1.481481,0.322559,-0.915141,0.086864,0,2002,1.0
3,-0.055722,0.940383,1.595019,0.357377,-0.179372,-0.183099,2.755945,-1.024735,-8.144928,0.484245,...,0.183283,0.025734,-0.410519,0.036473,0.200669,-0.912738,0.693920,0,2003,1.0
4,0.028089,-4.366486,0.755514,0.661548,-0.179372,-0.183099,0.887984,0.494700,0.038647,-0.398757,...,0.104840,0.707205,-0.615805,0.037037,0.395417,-0.908900,-0.334103,0,2004,0.0

In [164]:
random_data.to_csv('SRI_Country.csv')

<h1>8. SRI Country with Norm</h1>

In [167]:
df_8.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanSpecialist surgical workforce (per 100,000 population)","RanSuicide mortality rate (per 100,000 population)",RanTime required to build a warehouse (days),"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population)
0,-2.280608,0.091388,-2.035433,3.320021,-0.179372,-0.183099,-0.155835,0.307420,-8.328502,0.562510,...,-0.287500,0.979164,-0.614286,0.380384,0.405094,0.224774,0.074074,0.460967,-0.919919,0.933944
1,-2.622162,2.733320,0.669289,1.355332,-0.179372,-0.183099,3.845733,-0.777385,0.106280,-0.318351,...,0.100000,0.573935,-0.871429,3.122264,-0.400366,-0.232684,-0.592593,0.972914,-0.917543,1.588362
2,0.038077,0.215125,0.075741,0.209425,-0.179372,-0.183099,4.342282,0.696113,0.019324,1.519854,...,1.367344,0.642114,0.370603,1.099635,-0.429320,0.203743,-1.481481,0.322559,-0.915141,0.086864
3,-0.055722,0.940383,1.595019,0.357377,-0.179372,-0.183099,2.755945,-1.024735,-8.144928,0.484245,...,0.209242,1.071538,0.267800,0.183283,0.025734,-0.410519,0.036473,0.200669,-0.912738,0.693920
4,0.028089,-4.366486,0.755514,0.661548,-0.179372,-0.183099,0.887984,0.494700,0.038647,-0.398757,...,-0.575000,-0.037594,0.147535,0.104840,0.707205,-0.615805,0.037037,0.395417,-0.908900,-0.334103

In [166]:
cname = df_8.pop('Country Name')
year = df_8.pop('Year')
label = df_8.pop('Label')

In [168]:
column = df_8.columns.values.tolist()

In [169]:
transformer = Normalizer().fit(df_8)
df_8=transformer.transform(df_8)
df_8=pd.DataFrame(df_8, columns = column)
df_8.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanSpecialist surgical workforce (per 100,000 population)","RanSuicide mortality rate (per 100,000 population)",RanTime required to build a warehouse (days),"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population)
0,-0.007164,0.000287,-0.006394,0.010429,-0.000563,-0.000575,-0.000490,0.000966,-0.026163,0.001767,...,-0.000903,0.003076,-0.001930,0.001195,0.001273,0.000706,0.000233,0.001448,-0.002890,0.002934
1,-0.007958,0.008296,0.002031,0.004113,-0.000544,-0.000556,0.011672,-0.002359,0.000323,-0.000966,...,0.000303,0.001742,-0.002645,0.009476,-0.001215,-0.000706,-0.001799,0.002953,-0.002785,0.004821
2,0.000175,0.000991,0.000349,0.000965,-0.000826,-0.000843,0.019999,0.003206,0.000089,0.007000,...,0.006297,0.002957,0.001707,0.005065,-0.001977,0.000938,-0.006823,0.001486,-0.004215,0.000400
3,-0.000297,0.005006,0.008491,0.001902,-0.000955,-0.000975,0.014671,-0.005455,-0.043359,0.002578,...,0.001114,0.005704,0.001426,0.000976,0.000137,-0.002185,0.000194,0.001068,-0.004859,0.003694
4,0.000135,-0.020921,0.003620,0.003170,-0.000859,-0.000877,0.004254,0.002370,0.000185,-0.001911,...,-0.002755,-0.000180,0.000707,0.000502,0.003388,-0.002950,0.000177,0.001895,-0.004355,-0.001601

In [180]:
df_8['Country Name'] = list(df_7['Country Name'])
df_8['Year'] = list(df_7['Year'])
df_8['Label'] = list(df_7['Label'])

In [182]:
df_8.head()

,RanARI treatment (% of children under 5 taken to a health provider),RanAccess to electricity (% of population),RanAdjusted net national income (annual % growth),RanAdjusted net national income per capita (annual % growth),RanAdolescents out of school (% of lower secondary school age),RanAdults (ages 15+) and children (ages 0-14) newly infected with HIV,RanAdults (ages 15+) newly infected with HIV,"RanAir transport, passengers carried",RanBirths attended by skilled health staff (% of total),"RanBorrowers from commercial banks (per 1,000 adults)",...,"RanTotal alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)",RanTotal debt service (% of GNI),RanTrade (% of GDP),RanTravel services (% of commercial service exports),RanUHC service coverage index,RanUnmet need for contraception (% of married women ages 15-49),RanUrban population (% of total population),Country Name,Year,Label
0,-0.007164,0.000287,-0.006394,0.010429,-0.000563,-0.000575,-0.000490,0.000966,-0.026163,0.001767,...,0.001195,0.001273,0.000706,0.000233,0.001448,-0.002890,0.002934,0,2000,1.0
1,-0.007958,0.008296,0.002031,0.004113,-0.000544,-0.000556,0.011672,-0.002359,0.000323,-0.000966,...,0.009476,-0.001215,-0.000706,-0.001799,0.002953,-0.002785,0.004821,0,2001,1.0
2,0.000175,0.000991,0.000349,0.000965,-0.000826,-0.000843,0.019999,0.003206,0.000089,0.007000,...,0.005065,-0.001977,0.000938,-0.006823,0.001486,-0.004215,0.000400,0,2002,1.0
3,-0.000297,0.005006,0.008491,0.001902,-0.000955,-0.000975,0.014671,-0.005455,-0.043359,0.002578,...,0.000976,0.000137,-0.002185,0.000194,0.001068,-0.004859,0.003694,0,2003,1.0
4,0.000135,-0.020921,0.003620,0.003170,-0.000859,-0.000877,0.004254,0.002370,0.000185,-0.001911,...,0.000502,0.003388,-0.002950,0.000177,0.001895,-0.004355,-0.001601,0,2004,0.0

In [183]:
df_8.to_csv("SRI_Country_Norm.csv")

In [178]:
df.shape

(4280, 139)